---
title: "10_2_summary_corr_matrix.Rmd"
author: "Aidan Coyle"
date: "9/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This is a quick script meant to create a correlation matrix for the summary table we made in the script earlier

Code comes from Laura Spencer

Load packages, install if necessary

```{r}
# Add all required libraries here
list.of.packages <- c("tidyverse", "corrplot", "PerformanceAnalytics")
# Get names of all required packages that aren't installed
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
# Install all new packages
if(length(new.packages)) install.packages(new.packages)


# Load all required libraries
lapply(list.of.packages, FUN = function(X) {
  do.call("require", list(X))
})
```

Next, we'll read in the data and create our correlation matrix

```{r}
# Read in data
summ.dat <- read.csv("../data/indiv_crab_summary.csv")

# Rename first column to "Crab" to make it clearer
summ.dat <- rename(summ.dat, Crab = "ï..Crab")

# Convert as many data columns as possible to numeric
summ.dat$Crab <- as.numeric(as.factor(summ.dat$Crab))
summ.dat$Treatment <- as.numeric(ordered(summ.dat$Treatment, levels = c("Low", "Amb", "Elev")))
summ.dat$cPCR_positive <- as.numeric(as.factor(summ.dat$cPCR_positive))
summ.dat$imm_mature <- as.numeric(as.factor(summ.dat$imm_mature))

# Since we have NAs present for qPCR-SQ_mean_timepoint2, we'd need to drop that column
# To minimize the data loss, we'll create a new column of mean qPCR value
# For Crabs A-F, that means averaging the two columns. For Crabs G-I, that just means taking timepoint1
# To keep it in a spot we're familiar with, we'll just overwrite qPCR_SQ_mean_timepoint1
summ.dat$qPCR_SQ_mean_timepoint1 <- rowMeans(summ.dat[, c("qPCR_SQ_mean_timepoint1", "qPCR_SQ_mean_timepoint2")], na.rm = TRUE)
# We'll also rename the column and remove the timepoint 2 column
summ.dat <- rename(summ.dat, "qPCR_SQ_mean" = "qPCR_SQ_mean_timepoint1")
summ.dat <- select(summ.dat, -qPCR_SQ_mean_timepoint2)

# Remove columns that aren't informative
summ.dat <- select(summ.dat, -c(Crab, Uniq_ID, death, Timepoints))

# Check class of each column
str(summ.dat)
# All are ints or numeric, can continue

# Create correlation plot
cor(summ.dat) %>%
  corrplot(tl.cex = .45)
# Make it again, so we can save it as a .png
path <- "../output/correlation/all_variables_corr_dot_plot.png"
png(path)
cor(summ.dat) %>%
  corrplot(tl.cex = .45)
dev.off()

# Create chart of correlation
chart.Correlation(summ.dat, histogram = F, pch = 5)
# Make it again so we can save it as a .png
path <- "../output/correlation/all_variables_corr_chart.png"
png(path)
chart.Correlation(summ.dat, histogram = F, pch = 8)
dev.off()


table.Correlation(summ.dat)

```

